name = input("What is your name?")
print(f"hello{name}and welcome to CT8")
input("")
print(Were going to have a conversation about school ok? )
print("What school do you go to?")
input("")
print("I go to SAAS")
input("")
print("How is that going for you so far?")
input("")
print("Pretty good, school will always be exhausting tho")
input("")
print("Do you miss summer already?")
input("")
print("Very much so.")
input("")
print("Whats your favorite class right now and why?")
input("")
print("Probably visual because it has most of my friends and overall is just a chill class")
input("")
print("Thats good.")
input("")
print("Yup.")
