name = input("What is your name?")
print(f"hello {name} and welcome to CT8")
input("")
print("Were going to have a conversation about school ok?")
print("What school do you go to?")
input("")
print("oh cool!")
input("")
print("How is that going for you so far?")
input("")
print("thats nice")
input("")
print("Do you miss summer already?")
input("")
print("Me too, i love the sun")
input("")
print("Whats your favorite class right now and why?")
input("")
print("okay cool!")
input("")
print("who are your best friends at your school?")
input("")
print("sounds like nice people")
input("")
print("Do you like the lunch at SAAS?")
input("")
print("nice!")
input("")
print("Well thanks for chatting with me")
input("")
print(f"Talk to you soon, {name}")
